#!/usr/bin/env bash

set -eu

here=$(dirname $0)

hostnet=10.0.2.0/24
hostaddr=10.0.2.2
cores=$(nproc)
memsize=${MAXMEM:-4G}

## start system
case `uname` in
 'Darwin')
   accel=hvf
   ;;
 'Linux')
   accel=kvm
   ;;
  *)
    echo "WARNING: Cannot determine fast acceleration method, defaulting to slow Tiny Code Generator."
    accel=tcg
    ;;
esac
qemu-system-x86_64 \
    -accel $accel \
    -cpu max \
    -smp $cores \
    -m $memsize \
    -vga std \
    -device e1000,netdev=net0 \
    -netdev user,id=eth0,net="$hostnet",host="$hostaddr" \
    -hda "$here/artifact-hd.vmdk"
