#!/usr/bin/env bash

set -eu

here=$(dirname $0)

hostnet=10.0.2.0/24
hostaddr=10.0.2.2 # used in netboot/pxelinux.cfg/default
memsize=2G
imgsize=4G

if [ $# -ne 1 ]; then
  echo "Usage: $0 TARGETDIR"
fi
target=$1

## create target directory
echo "Create target directory"
if [ -e $target ]; then
    echo "Target directory $target already exists."
    exit 1
fi
mkdir -p "$target"

## create disk image
echo "Create disk image"
img="$target/box.img"
qemu-img create -f qcow2 "$img" $imgsize

## create disk image
cp "$here/bin/*" "$target/"

## install system
case `uname` in
 'Darwin')
   accel=hvf
   ;;
 'Linux')
   accel=kvm
   ;;
  *)
    echo "WARNING: Cannot determine fast acceleration method, defaulting to slow Tiny Code Generator."
    accel=tcg
    ;;
esac
echo "Running VM for installation (shutdown when done)"
netboot="$here/debian-10-netboot"
qemu-system-x86_64 \
    -accel $accel \
    -cpu max \
    -m $memsize \
    -vga std \
    -device e1000,netdev=eth0 \
    -netdev user,id=eth0,net="$hostnet",host="$hostaddr",tftp="$netboot",bootfile=pxelinux.0 \
    -hda "$img"
